---
title: "Moloco Data Analyst Intern Test - Analytics"
author: "Esther Lim"
date: "5/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(gsheet)
library(dplyr)
library(magrittr)
library(lubridate)
```

## Analytics
```{r}
# download google sheet as a table
data <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1AV-A1uhQqvF6h0_a-fupFQIHv6W7-vNm88AYh_WzeB0/edit#gid=1326833441", sheetid = "Q1 Analytics")
```

### 1
```{r}
data %>%
  filter(country_id == "BDV") %>% # consider only the rows with country_id = "BDV"
  group_by(site_id) %>% # for each site_id, compute the number of unique user_id
  summarize(count = n_distinct(user_id))
```
5NPAU has the largest number with 544 unique users.

### 2
```{r}
data %>%
  filter(ts >= as.POSIXct("2019-02-03 00:00:00","UTC") &  # filter between 2019-02-03 00:00:00 and
           ts <= as.POSIXct("2019-02-04 23:59:59","UTC")) %>% # 2019-02-04 23:59:59
  group_by(user_id, site_id) %>% # group by user and site
  count() %>% 
  filter(n > 10) # visited more than 10 times
```
(LC06C3, N0OTG, 25)
(LC3A59, N0OTG, 26)
(LC3C7E, 3POLC, 15)
(LC3C9D, N0OTG, 17)

### 3
```{r}
data %>%
  group_by(user_id) %>% # group by user
  filter(ts == max(ts)) %>% # filter the unique users by their last visit
  group_by(site_id) %>% # group by site
  summarize(count = n()) %>% 
  top_n(3) # select top three sites
```
(5NPAU, 992)
(N0OTG, 561)
(QGO3G, 289)

### 4
```{r}
data %>% 
  group_by(user_id) %>% # group by user
  mutate(first = site_id[ts == min(ts)] ) %>%  # find the first site user visited
  mutate(last = site_id[ts == max(ts)]) %>% # find the last site user visited
  mutate(same = isTRUE(first == last)) %>% # find whether the first and last sites are the same
  summarize(count = sum(same)) %>% # count the number of users whose first/last visited sites are the same
  summarize(count = n())
```
1916 users

